/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm_desktop.ADD;

import characters.ADD.DD_Spell;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolas
 */
public class ADD_PCSubPanelSpells extends javax.swing.JPanel {
  
  private int id;

  /**
   * Creates new form ADD_PC_SubPanelSpells
   */
  public ADD_PCSubPanelSpells() {
    initComponents();
    
    setSize(232,284);
    setVisible(true);
  }
  
  public void setSpells(ArrayList<DD_Spell> spells){
    DefaultTableModel model = (DefaultTableModel) jtableSpells.getModel();
    for(DD_Spell spell : spells){
      model.addRow(new Object[]{spell.getName(),spell.getSchool(),spell.getAttribute(),spell.getLevel()});
    }
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jtableSpells = new javax.swing.JTable();

    setMaximumSize(new java.awt.Dimension(232, 284));
    setMinimumSize(new java.awt.Dimension(232, 284));
    setPreferredSize(new java.awt.Dimension(232, 284));

    jtableSpells.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Name", "School", "Attribute", "Level"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    jScrollPane1.setViewportView(jtableSpells);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jtableSpells;
  // End of variables declaration//GEN-END:variables
}
