/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm_desktop.scenario;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import rpgTools.GameType;
import xml.XMLParser;

/**
 *
 * @author nicolas
 */
public class ScenarioCreation extends javax.swing.JPanel {

  private GameType game;
  
  /**
   * Creates new form ScenarioCreation
   */
  public ScenarioCreation() {
    initComponents();
    setSize(760,470);
    setVisible(true);
  }
  
  public void setGameType(String game){
    this.game = new GameType(game);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jtfTitle = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jtextSummary = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    jtextPrimeEvents = new javax.swing.JTextArea();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    jtextSecondEvents = new javax.swing.JTextArea();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane4 = new javax.swing.JScrollPane();
    jtextRandomEvents = new javax.swing.JTextArea();
    jLabel3 = new javax.swing.JLabel();
    jbtnSaveScenario = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jtfSuccess = new javax.swing.JTextField();
    jtfFailure = new javax.swing.JTextField();

    setMaximumSize(new java.awt.Dimension(760, 470));
    setMinimumSize(new java.awt.Dimension(760, 470));

    jtfTitle.setText("Scenario Title");

    jtextSummary.setColumns(20);
    jtextSummary.setLineWrap(true);
    jtextSummary.setRows(5);
    jScrollPane1.setViewportView(jtextSummary);

    jtextPrimeEvents.setColumns(20);
    jtextPrimeEvents.setLineWrap(true);
    jtextPrimeEvents.setRows(5);
    jScrollPane2.setViewportView(jtextPrimeEvents);

    jLabel1.setText("Primary Events");

    jtextSecondEvents.setColumns(20);
    jtextSecondEvents.setLineWrap(true);
    jtextSecondEvents.setRows(5);
    jScrollPane3.setViewportView(jtextSecondEvents);

    jLabel2.setText("Secondary Events");

    jtextRandomEvents.setColumns(20);
    jtextRandomEvents.setLineWrap(true);
    jtextRandomEvents.setRows(5);
    jScrollPane4.setViewportView(jtextRandomEvents);

    jLabel3.setText("Random Events");

    jbtnSaveScenario.setText("Save");
    jbtnSaveScenario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbtnSaveScenarioActionPerformed(evt);
      }
    });

    jLabel4.setText("Success: ");

    jLabel5.setText("Failure: ");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSaveScenario))))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jScrollPane2)
              .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
              .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel3)
                  .addComponent(jLabel2)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                      .addComponent(jLabel5)
                      .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(jtfSuccess)
                      .addComponent(jtfFailure, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE)))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jbtnSaveScenario))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel1)
        .addGap(3, 3, 3)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jtfSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(jtfFailure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(41, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jbtnSaveScenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveScenarioActionPerformed
    XMLParser xml = new XMLParser();
    HashMap<String,ArrayList<String>> toSave = new HashMap<>();
    
    // Title
    String title = jtfTitle.getText();
    ArrayList<String> tmpTitle = new ArrayList<>();
    tmpTitle.add(title);
    toSave.put("title",tmpTitle);
    
    // Summary
    Document doc = jtextSummary.getDocument();
    try {
      String tmp = doc.getText(0,doc.getLength());
      ArrayList<String> tmpSummary = new ArrayList<>();
      tmpSummary.add(tmp);
      toSave.put("summary",tmpSummary);
    } catch (BadLocationException ex) {
      Logger.getLogger(ScenarioCreation.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    // Prime Events
    doc = jtextPrimeEvents.getDocument();
    try{
      String tmp = doc.getText(0,doc.getLength());
      String[] parts = tmp.split("\n");    // FIXME:!!!!!!!!!!!!!!
      ArrayList<String> tmpPrime = new ArrayList<>();
      for(int i = 0 ; i < parts.length ; ++i){
        tmpPrime.add(parts[i]);
      }
      toSave.put("prime",tmpPrime);
    }
    catch(BadLocationException e){
      e.printStackTrace();
    }
    
    // Second Events
    doc = jtextSecondEvents.getDocument();
    try{
      String tmp = doc.getText(0,doc.getLength());
      String[] parts = tmp.split("\n");
      ArrayList<String> tmpSecond = new ArrayList<>();
      for(int i = 0 ; i < parts.length ; ++i){
        tmpSecond.add(parts[i]);
      }
      toSave.put("second",tmpSecond);
    }
    catch(BadLocationException e){
      e.printStackTrace();
    }
    
    // Random Events
    doc = jtextRandomEvents.getDocument();
    try{
      String tmp = doc.getText(0,doc.getLength());
      String[] parts = tmp.split("\n");
      ArrayList<String> tmpRandom = new ArrayList<>();
      for(int i = 0 ; i < parts.length ; ++i){
        tmpRandom.add(parts[i]);
      }
      toSave.put("random",tmpRandom);
    }
    catch(BadLocationException e){
      e.printStackTrace();
    }
    
    // Success and Failure
    ArrayList<String> tmpSuccess = new ArrayList<>();
    tmpSuccess.add(jtfSuccess.getText());
    toSave.put("success",tmpSuccess);
    
    ArrayList<String> tmpFailure = new ArrayList<>();
    tmpFailure.add(jtfFailure.getText());
    toSave.put("failure",tmpFailure);
    
    xml.saveScenario(toSave, game);
  }//GEN-LAST:event_jbtnSaveScenarioActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JButton jbtnSaveScenario;
  private javax.swing.JTextArea jtextPrimeEvents;
  private javax.swing.JTextArea jtextRandomEvents;
  private javax.swing.JTextArea jtextSecondEvents;
  private javax.swing.JTextArea jtextSummary;
  private javax.swing.JTextField jtfFailure;
  private javax.swing.JTextField jtfSuccess;
  private javax.swing.JTextField jtfTitle;
  // End of variables declaration//GEN-END:variables
}
