package ihm_desktop.PATIENT;

import ihm_desktop.MainFrame;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolas
 */
public class P13_PCPanel extends javax.swing.JPanel {

  /**
   * Creates new form jPanelPatient13
   */
  public P13_PCPanel() {
    initComponents();
    
    setSize(258,470);
    setVisible(true);
    // THIS HAS TO BE 258 WIDTH x 470 HEIGHT!!
  }
  
  public void setGenerics(String player, String character, int age, double weight, double size, boolean gender){
    jlblPlayer.setText("Player: " + player);
    jlblCharacter.setText("Character: " + character);
    jlblAge.setText("Age: " + Integer.toString(age));
    jlblWeight.setText("Weight: " + Double.toString(weight));
    jlblSize.setText("Size: " + Double.toString(size));
    jlblGender.setText("Gender: " + (gender ? "woman" : "man"));
  }
  
  public void setSpecifics(String supervisor, String surname, String room, int seniority, int vitality, int lucidity, int coldblood,HashMap<String,Integer>lineaments){
    jlblSupervisor.setText("Supervisor: " + supervisor);
    jlblSurname.setText("Surname: " + surname);
    jlblRoom.setText("Room: " + room);
    jlblSeniority.setText("Seniority: " + (seniority < 10 ? "0" : "") + Integer.toString(seniority));
    jlblVitality.setText("Vitality: " + (vitality < 10 ? "0" : "") + Integer.toString(vitality));
    jlblLucidity.setText("Lucidity: " + (lucidity < 10 ? "0" : "") + Integer.toString(lucidity));
    jlblColdblood.setText("Cold blood: " + (coldblood < 10 ? "0" : "") + Integer.toString(coldblood));
    DefaultTableModel model = (DefaultTableModel) jtableLineaments.getModel();
    for(String key : lineaments.keySet()){
      model.addRow(new Object[]{key,String.valueOf(lineaments.get(key))});
    }
  }
  
  public int getVitality(){
    return Integer.parseInt(jlblVitality.getText().split(": ")[1]);
  }
  public int getColdblood(){
    return Integer.parseInt(jlblColdblood.getText().split(": ")[1]);
  }
  public int getLucidity(){
    return Integer.parseInt(jlblLucidity.getText().split(": ")[1]);
  }
  public int getSeniority(){
    return Integer.parseInt(jlblSeniority.getText().split(": ")[1]);
  }
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jlblPlayer = new javax.swing.JLabel();
    jlblCharacter = new javax.swing.JLabel();
    jlblAge = new javax.swing.JLabel();
    jlblWeight = new javax.swing.JLabel();
    jlblSize = new javax.swing.JLabel();
    jlblGender = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jlblSurname = new javax.swing.JLabel();
    jlblSupervisor = new javax.swing.JLabel();
    jlblRoom = new javax.swing.JLabel();
    jlblSeniority = new javax.swing.JLabel();
    jlblLucidity = new javax.swing.JLabel();
    jlblVitality = new javax.swing.JLabel();
    jlblColdblood = new javax.swing.JLabel();
    lucidityPlus = new javax.swing.JButton();
    lucidityMinus = new javax.swing.JButton();
    vitalityPlus = new javax.swing.JButton();
    vitalityMinus = new javax.swing.JButton();
    coldbloodPlus = new javax.swing.JButton();
    coldbloodMinus = new javax.swing.JButton();
    seniorityPlus = new javax.swing.JButton();
    seniorityMinus = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jtableLineaments = new javax.swing.JTable();

    setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    setMaximumSize(new java.awt.Dimension(258, 470));
    setMinimumSize(new java.awt.Dimension(258, 470));
    setPreferredSize(new java.awt.Dimension(258, 470));

    jlblPlayer.setText("Player:");

    jlblCharacter.setText("Character:");

    jlblAge.setText("Age:");

    jlblWeight.setText("Weight:");

    jlblSize.setText("Size:");

    jlblGender.setText("Gender:");

    jlblSurname.setText("Surnom:");

    jlblSupervisor.setText("Supervisor:");

    jlblRoom.setText("Room:");

    jlblSeniority.setText("Seniority:");

    jlblLucidity.setText("Lucidity:");

    jlblVitality.setText("Vitality:");

    jlblColdblood.setText("Cold Blood:");

    lucidityPlus.setText("+");
    lucidityPlus.setName("lPlus"); // NOI18N
    lucidityPlus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        plusValue(evt);
      }
    });

    lucidityMinus.setText("-");
    lucidityMinus.setName("lMinus"); // NOI18N
    lucidityMinus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        plusValue(evt);
      }
    });

    vitalityPlus.setText("+");
    vitalityPlus.setName("vPlus"); // NOI18N
    vitalityPlus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        plusValue(evt);
      }
    });

    vitalityMinus.setText("-");
    vitalityMinus.setName("vMinus"); // NOI18N
    vitalityMinus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        plusValue(evt);
      }
    });

    coldbloodPlus.setText("+");
    coldbloodPlus.setName("cPlus"); // NOI18N
    coldbloodPlus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        plusValue(evt);
      }
    });

    coldbloodMinus.setText("-");
    coldbloodMinus.setName("cMinus"); // NOI18N
    coldbloodMinus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        plusValue(evt);
      }
    });

    seniorityPlus.setText("-");
    seniorityPlus.setName("sMinus"); // NOI18N
    seniorityPlus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        plusValue(evt);
      }
    });

    seniorityMinus.setText("+");
    seniorityMinus.setName("sPlus"); // NOI18N
    seniorityMinus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        plusValue(evt);
      }
    });

    jtableLineaments.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Lineaments", "Value"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, true
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(jtableLineaments);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(jlblSeniority)
                  .addGap(112, 112, 112))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblVitality)
                    .addComponent(jlblLucidity))
                  .addGap(120, 120, 120)))
              .addComponent(jlblPlayer)
              .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jlblCharacter)
              .addComponent(jlblAge)
              .addComponent(jlblWeight)
              .addComponent(jlblSize)
              .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jlblGender))
              .addComponent(jlblSurname)
              .addComponent(jlblRoom)
              .addComponent(jlblSupervisor))
            .addGap(13, 13, 13))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jlblColdblood)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(lucidityPlus)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lucidityMinus))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(vitalityPlus)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(vitalityMinus))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(seniorityMinus)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(seniorityPlus))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(coldbloodPlus)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(coldbloodMinus))))
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(11, 11, 11))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jlblPlayer)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jlblCharacter)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jlblAge)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jlblWeight)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jlblSize)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jlblGender)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jlblSurname)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jlblRoom)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jlblSupervisor)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jlblSeniority)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jlblLucidity)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jlblVitality)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jlblColdblood))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(seniorityMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(seniorityPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lucidityPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lucidityMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(vitalityPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(vitalityMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(coldbloodPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(coldbloodMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(28, 28, 28)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void plusValue(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusValue
    
    int tmpSeniority,tmpVitality,tmpLucidity,tmpColdblood;
    
    switch(((JButton)evt.getSource()).getName()){
      case "sPlus":
        tmpSeniority = (Integer.parseInt(jlblSeniority.getText().split(": ")[1]) + 1) > 99 ? 99 : (Integer.parseInt(jlblSeniority.getText().split(": ")[1]) + 1) ;
        jlblSeniority.setText("Seniority: " + (tmpSeniority < 10 ? "0" : "") + Integer.toString(tmpSeniority));
        break;
      case "sMinus":
        tmpSeniority = (Integer.parseInt(jlblSeniority.getText().split(": ")[1]) - 1) < 0 ? 0 : (Integer.parseInt(jlblSeniority.getText().split(": ")[1]) - 1) ;
        jlblSeniority.setText("Seniority: " + (tmpSeniority < 10 ? "0" : "") + Integer.toString(tmpSeniority));
        break;
      case "lPlus":
        tmpLucidity = (Integer.parseInt(jlblLucidity.getText().split(": ")[1]) + 1) > 99 ? 99 : (Integer.parseInt(jlblLucidity.getText().split(": ")[1]) + 1) ;
        jlblLucidity.setText("Lucidity: " + (tmpLucidity < 10 ? "0" : "") + Integer.toString(tmpLucidity));
        break;
      case "lMinus":
        tmpLucidity = (Integer.parseInt(jlblLucidity.getText().split(": ")[1]) - 1) < 0 ? 0 : (Integer.parseInt(jlblLucidity.getText().split(": ")[1]) - 1) ;
        jlblLucidity.setText("Lucidity: " + (tmpLucidity < 10 ? "0" : "") + Integer.toString(tmpLucidity));
        break;
      case "vPlus":
        tmpVitality = (Integer.parseInt(jlblVitality.getText().split(": ")[1]) + 1) > 99 ? 99 : (Integer.parseInt(jlblVitality.getText().split(": ")[1]) + 1) ;
        jlblVitality.setText("Vitality: " + (tmpVitality < 10 ? "0" : "") + Integer.toString(tmpVitality));
        break;
      case "vMinus":
        tmpVitality = (Integer.parseInt(jlblVitality.getText().split(": ")[1]) - 1) < 0 ? 0 : (Integer.parseInt(jlblVitality.getText().split(": ")[1]) - 1) ;
        jlblVitality.setText("Vitality: " + (tmpVitality < 10 ? "0" : "") + Integer.toString(tmpVitality));
        break;
      case "cPlus":
        tmpColdblood = (Integer.parseInt(jlblColdblood.getText().split(": ")[1]) + 1) > 99 ? 99 : (Integer.parseInt(jlblColdblood.getText().split(": ")[1]) + 1) ;
        jlblColdblood.setText("Cold blood: " + (tmpColdblood < 10 ? "0" : "") + Integer.toString(tmpColdblood));
        break;
      case "cMinus":
        tmpColdblood = (Integer.parseInt(jlblColdblood.getText().split(": ")[1]) - 1) < 0 ? 0 : (Integer.parseInt(jlblColdblood.getText().split(": ")[1]) - 1) ;
        jlblColdblood.setText("Cold blood: " + (tmpColdblood < 10 ? "0" : "") + Integer.toString(tmpColdblood));
        break;
      
      default:
        break;
    }//switch
    
    ((MainFrame)SwingUtilities.getWindowAncestor(this)).setModification(this.jlblPlayer.getText());
    
  }//GEN-LAST:event_plusValue


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton coldbloodMinus;
  private javax.swing.JButton coldbloodPlus;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JLabel jlblAge;
  private javax.swing.JLabel jlblCharacter;
  private javax.swing.JLabel jlblColdblood;
  private javax.swing.JLabel jlblGender;
  private javax.swing.JLabel jlblLucidity;
  private javax.swing.JLabel jlblPlayer;
  private javax.swing.JLabel jlblRoom;
  private javax.swing.JLabel jlblSeniority;
  private javax.swing.JLabel jlblSize;
  private javax.swing.JLabel jlblSupervisor;
  private javax.swing.JLabel jlblSurname;
  private javax.swing.JLabel jlblVitality;
  private javax.swing.JLabel jlblWeight;
  private javax.swing.JTable jtableLineaments;
  private javax.swing.JButton lucidityMinus;
  private javax.swing.JButton lucidityPlus;
  private javax.swing.JButton seniorityMinus;
  private javax.swing.JButton seniorityPlus;
  private javax.swing.JButton vitalityMinus;
  private javax.swing.JButton vitalityPlus;
  // End of variables declaration//GEN-END:variables
}
